### ISSUE TITLE
Windows builds?

### ISSUE THREAD

**Issue by 3oheicrw** [dbsoft/White-Star#1]
As I see your browser added support for Windows just recently. What about providing Windows builds? I'm not bother about Windows XP as my PC is Windows 7 64 bit. Your Mac is Intel 64 bit too, isn't it? So what about at least a Windows 7+ 64 bit build? Installer is not needed. A zipped package is enough. I know Mac is very powerful system so setting up a Windows 7 64 bit VM is not that difficult for you. My PC on the other hand has real troubling building large code base like White Star. It will took hours.

**Comment by dbsoft** [comment]
Hi, I am able to do Windows builds, my plan is to release builds for Windows XP at some point.  I didn't really want to release builds for Windows 7 and later because I was planning on not trying to compete directly with Pale Moon.  

However due to some recent events (regarding my attempted acquisition of Basilisk) I am wondering if I should bother trying to play nice with Moonchild or if I should just do what people ask of me.

I will think on it.

**Comment by 3oheicrw** [comment]
> Hi, I am able to do Windows builds, my plan is to release builds for Windows XP at some point.
>
Are your browser able to build for Windows XP yet? As you forked from Pale Moon 29.4.4 which have Windows XP support removed for a long time and I didn't see any commits of yours to revert this changes back. This maybe very difficult to do in the modern UXP codebase that you forked from.

Windows XP users always have @roytam1 and his Pale Moon builds for Windows XP. The space left by MyPal I think was already filled by @roytam1's work and he has do this for a long time. If you want to make Windows builds I think it's easier to just target Windows 7+. Your browser is a complete fork whose binary name is changed, unlike @roytam1's unofficial builds where the binary is still named palemoon.exe.

**Comment by dbsoft** [comment]
Ah that is cool, I had no idea, you should really consider changing the versioning scheme.  It makes your builds seem out of date.

**Comment by dbsoft** [comment]
> @dbsoft I think you should just forget about Windows XP.

I just don't see what the point would be to provide Windows binaries that don't provide something beyond what Pale Moon already provides.

**Comment by 3oheicrw** [comment]
> > @dbsoft I think you should just forget about Windows XP.
> 
> I just don't see what the point would be to provide Windows binaries that don't provide something beyond what Pale Moon already provides.

Maybe something like this?

https://forum.palemoon.org/viewtopic.php?f=40&t=27873

**Comment by dbsoft** [comment]
> Maybe something like this?
> 
> https://forum.palemoon.org/viewtopic.php?f=40&t=27873

Yeah potentially, if people have a specific build that would be useful that is not provided by Pale Moon itself.

**Comment by dbsoft** [comment]
@roytam1 I checked out your builds, you seem to have the security patches, which is good but you are missing a lot of the features the Pale Moon team has added... like the Opportunistic Encryption and Dark/Light Mode support. (Just a few examples easily seen on the surface).  Are you planning on bringing those in or is it essentially stuck at the 27 feature set?

**Comment by roytam1** [comment]
> Opportunistic Encryption
I think I had it in my tree.

> Dark/Light Mode support
this breaks complete theming

**Comment by dbsoft** [comment]
> > Opportunistic Encryption
> > I think I had it in my tree.

Well perhaps the back end support is there but the front end user interface to toggle the options is missing.

> > Dark/Light Mode support
> > this breaks complete theming

Not sure if you know what it is, there is an option in the new Pale Moon where you can pick the mode Pale Moon reports to web sites, to control if they give you the dark or light mode version of the web interface.  You can pick Light, Dark or Unspecified to not report a mode at all.

**Comment by roytam1** [comment]
> Both of these UI features are present in Pale Moon, White Star and Mypal.... but are missing from your build.

since my front-end code are de-railed from upstream since 28.10 so it could be the case.

**Comment by 3oheicrw** [comment]
> @roytam1 I checked out your builds, you seem to have the security patches, which is good but you are missing a lot of the features the Pale Moon team has added... like the Opportunistic Encryption and Dark/Light Mode support. (Just a few examples easily seen on the surface). Are you planning on bringing those in or is it essentially stuck at the 27 feature set?

His Pale Moon 27 is actually derived from Arctic-Fox. His Pale Moon 28 is his own fork of Pale Moon 28 and not synced with upstream yet even though he's still update the UXP backend. His frontend is pretty much stuck at Pale Moon 28.10. He has no Pale Moon 29 builds.

**Comment by 3oheicrw** [comment]
@dbsoft I personally think UXP is somewhat like the Java Runtime Environment. If you could pulling needed changes from his Windows XP supported UXP to your UXP then I think you could just build WhiteStar for Windows XP as is as I don't think there is any needs to change the frontend code. @roytam1 Please correct me if I'm wrong.

**Comment by dbsoft** [comment]
> @dbsoft I personally think UXP is somewhat like the Java Runtime Environment. If you could pulling needed changes from his Windows XP supported UXP to your UXP then I think you could just build WhiteStar for Windows XP as is as I don't think there is any needs to change the frontend code. @roytam1 Please correct me if I'm wrong.

Not sure about the comparison to the JRE, but generally speaking yes the white start FE should build with roytam1's version of UXP.  There might be minor changes required though.

**Comment by 3oheicrw** [comment]
The current situation changed, I think he will rejoin with the Pale Moon project, so a Windows build is very unlikely.

**Comment by dbsoft** [comment]
I still might do Windows XP builds in the future, if Mypal doesn't get resurrected, but the focus is back on the Mac end of things for sure... and with the reunification of UXP at least... it means less work for me maintaining the UXP fork.  For now I'll still be doing White Star builds, starting with version 31 though, it will be using the official Pale Moon version of UXP instead of my fork.
